---
- name: debug event
  debug: var=event

- name: set apt proxy
  include_tasks: apt-proxy.yml
  when: set_proxy == 1

- name: set snap proxy
  include_tasks: snap-proxy.yml
  when: set_proxy == 1

- name: set security
  include_tasks: security.yml
  when: set_security == 1

- name: set netplan
  include_tasks: netplan.yml
  when: set_netplan == 1

