---
- name: set allow hosts
  lineinfile:
    path: /etc/hosts.allow
    regexp: '^sshd:'
    insertafter: EOF
    line: "sshd: {{ allow_sshd_hosts }}"
  become: yes
  when: allow_sshd_hosts is defined

- name: unset allow hosts
  lineinfile:
    path: /etc/hosts.allow
    regexp: '^sshd:'
    state: absent
  become: yes
  when: allow_sshd_hosts is undefined


- name: set deny hosts
  lineinfile:
    path: /etc/hosts.deny
    regexp: '^sshd:'
    insertafter: EOF
    line: "sshd: all"
  become: yes
  when: allow_sshd_hosts is defined

- name: unset deny hosts
  lineinfile:
    path: /etc/hosts.deny
    regexp: '^sshd:'
    state: absent
  become: yes
  when: allow_sshd_hosts is undefined

