---
#
- name: debug
  debug:
   msg: "{{ difok }}"

- name: Install pwmake
  apt:
    name:
      - libpwquality-tools
    state: latest
  become: yes

- name: set password quality
  lineinfile:
    path: /etc/security/pwquality.conf
#    backrefs: yes
    regexp: '{{ item.regexp }}'
    insertafter: '{{ item.after }}'
    line: '{{ item.line }}'
  become: yes
  with_items:
  - regexp: '^difok'
    after: '^^# difok'
    line: 'difok = {{ difok }}'
  - regexp: '^minlen'
    after: '^^# minlen'
    line: 'minlen = {{ minlen }}'
  - regexp: '^dcredit'
    after: '^^# dcredit'
    line: 'dcredit = {{ dcredit }}'
  - regexp: '^ucredit'
    after: '^^# ucredit'
    line: 'ucredit = {{ ucredit }}'
  - regexp: '^lcredit'
    after: '^^# lcredit'
    line: 'lcredit = {{ lcredit }}'
  - regexp: '^ocredit'
    after: '^^# ocredit'
    line: 'ocredit = {{ ocredit }}'
  - regexp: '^minclass'
    after: '^^# minclass'
    line: 'minclass = {{ minclass }}'
  - regexp: '^gecoscheck'
    after: '^^# gecoscheck'
    line: 'gecoscheck = 1'
  - regexp: '^dictcheck'
    after: '^^# dictcheck'
    line: 'dictcheck = 1'
  - regexp: '^usercheck'
    after: '^^# usercheck'
    line: 'usercheck = 1'
  - regexp: '^enforcing'
    after: '^^# enforcing'
    line: 'enforcing = 1'
  when: secure > 0

- name: unset password quality
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '{{ item }}'
    state: absent
  become: yes
  with_items:
  - '^difok'
  - '^minlen'
  - '^dcredit'
  - '^ucredit'
  - '^lcredit'
  - '^ocredit'
  - '^minclass'
  - '^gecoscheck'
  - '^dictcheck'
  - '^usercheck'
  - '^enforcing'
  when: secure == 0 or secure is undefined

