---
# name: user name
# pass: hashed password
# file: clear onetime password in file
- name: debug shadow
  debug: var=shadow


- name: get onetime password
  register: onepass
  shell: 
    cmd: "cat {{ shadow.file }} | cut -d, -f 2"
  delegate_to: "{{ control_ipv4 }}"
  become: true
  changed_when: false


- name: get password in shadow on control
  register: control_pass
  shell: 
    cmd: "grep -e '^{{ shadow.name }}:' /etc/shadow | cut -d: -f 2"
  delegate_to: "{{ control_ipv4 }}"
  become: true
  changed_when: false

- name: get elapsed day in shadow on control
  register: control_elap
  shell: 
    cmd: "grep -e '^{{ shadow.name }}:' /etc/shadow | cut -d: -f 3"
  delegate_to: "{{ control_ipv4 }}"
  become: true
  changed_when: false


- name: get password in shadow on manege
  register: manage_pass
  shell: 
    cmd: "grep -e '^{{ shadow.name }}:' /etc/shadow | cut -d: -f 2"
  become: true
  changed_when: false

- name: get elapsed day in shadow on manege
  register: manage_elap
  shell: 
    cmd: "grep -e '^{{ shadow.name }}:' /etc/shadow | cut -d: -f 3"
  become: true
  changed_when: false


- name: debug user
  debug:
    msg: "{{ item }}"
  with_items:
  - "username:{{ user.name }}, onepass:{{ onepass.stdout }}"
  - "control:{{ control_elap.stdout }}, manege:{{ control_elap.stdout }}"
  - "control_pass={{ control_pass.stdout }}"
  - "manage_pass={{ manage_pass.stdout }}"

- name: change password
  include_tasks: password_change.yml
  with_items:
  - name: "{{ shadow.name }}"
    passwd: "{{ control_pass.stdout }}"
    file: "{{ shadow.file }}"
  loop_control:
    loop_var: hashed
  when:
  - control_pass.stdout != ""
  - control_pass.stdout != onepass.stdout
  - control_elap.stdout | int >= manage_elap.stdout | int or manage_pass == "*"

