---
- name: debug control
  debug: var=control

- name: change password
  user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
#    update_password: on_create
  become: true

- name: info password
  debug:
    msg: "INFO: ID:{{ item.name }},PW:{{ item.text }}"
  when: item.text is defined

