---
# name: user name
# pass: hashed password
# file: clear onetime password in file
- name: debug hashed
  debug: var=hashed


- name: debug elaped
  debug:
    msg: "control:{{ control_elap.stdout }}, manege:{{ control_elap.stdout }}"

- name: change password by shadow password
  user:
    name: "{{ hashed.name }}"
    password: "{{ hashed.passwd }}"
  become: true

- name: get expire day
  register: now_sec
  command: "date +%s"
  delegate_to: localhost
  changed_when: false

- name: next time of change password
  vars:
    expire_days: 400
    expire_sec: "{{ now_sec.stdout | int + 60 * 60 * 24 * expire_days | int }}"
  user:
    name: "{{ hashed.name }}"
    expires: "{{ expire_sec }}"
  become: true
  delegate_to: "{{ control_ipv4 }}"

- name: flag of change password by file stat for check
  file: 
    path: "{{ hashed.file }}"
    mode: 0640
  become: true
  delegate_to: "{{ control_ipv4 }}"


